### ISSUE TITLE
业务与用例图问题

### ISSUE THREAD

**Issue by ZhangJiaQiao** [Baoleme/Dashboard#2]
1.对于顾客来说，点餐是其主要业务，不应作为一个大的用例，点餐系统是服务于这个业务的
2.顾客缺少扫码用例
3.对于商家与顾客的业务分离会不会好点，画成两张用例图，一张商家管理系统，一种顾客点餐系统
4.对于后台，有无管理商家与顾客系统的需求

**Comment by zhoumumu** [comment]
1&3.我觉得3说的有道理；1说的基本同意，但不是很明你的确修改意见，改成两个分开的两张图你觉得还有不对的地方吗？
2.有哇
4.有道理

**Comment by zhoumumu** [comment]
第一，1&3的问题跟@ZhangJiaQiao同志私下交流过了，是一个意思，觉得改两张图比较好。但然后我也去问了老师，老师表示看成一个完整的系统也没问题，这要看设计师的意图。我觉得画图根本目的还是要在团队内形成对用例的规范、对需求的共识，因此形式上要不要分开关系不大啦。不过这到给我们提了个醒，直接丢出两个用例相关的文件夹给人看，的确对团队外部的人不太友好，之后我会整理一个用例的readme。
第二，后台的确应该有管理商家的需求，不过目前的迭代并没有考虑这个需求，我们会在需求文档中做好记录，感谢！
