### ISSUE TITLE
领域模型问题

### ISSUE THREAD

**Issue by ZhangJiaQiao** [Baoleme/Dashboard#3]
1.历史订单改成订单列表可能会好点，订单有状态，可能处于未接单状态
2.购物篮是否为顾客所有，应有联系
3.模型中顾客与座位的关系，座位与二维码的关系未体现，座位是否座位附属商家下的一个实体
4.Dashboard的结构最好改成老师课上的形式

**Comment by zhoumumu** [comment]
1.历史订单会在页面中以列表的形式呈现，在领域模型中也显示的是has * 订单，订单has * 状态。
2.有道理。
3.我认为不必把座位当成一个实体加以考虑，它除了一个号码没有其他东西。而这个号码信息包含在二维码中，随着用户的扫码请求与他即将下的订单建立联系，随后订单中就包含了桌号信息，商家可以正常上菜。桌号与顾客的间接联系不重要。
4.我觉得目前结构挺好的，有计划做成一个GitHub page，再慢慢调整吧。
